# Site settings
name: 谭礼渊的博客
author: TanLiYuan
email: undefined4me@gmail.com
url: http://tanliyuan.top

#主题
theme_author: M/J
theme_site: https://github.com/maoxiaoke/maoxiaoke.github.io

github: https://github.com/tanliyuan/
baseurl: ""  #根目录
description: 假如生活欺骗了你，不要悲伤，不要哭泣。
motto: 这城市风很大，寂寞的人总是晚回家。
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: tanliyuan
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : tanliyuan

port: 4001